package femtoXML;

import java.util.Map;

/** 
 * An XMLHandler receives and handles the lexical events generated by scanning an XML document.
 * 
 * @author sufrin
 *
 */

public interface XMLHandler
{
  public void startElement(String kind, Map<String, String> atts); // <kind attr1="val1" ...

  public void endElement(String kind);                             // </kind>

  public void commentCharacters(CharSequence text);                // <!-- ... -->

  public void wordCharacters(CharSequence text);                   // ...

  public void startDocument();

  public void endDocument();

  public String decodeEntity(String entity);                       // &entityname;
}
