package femtoXML;

/** XMLSyntaxError errors are generated by scanners and parsers. */
@SuppressWarnings("serial")
public class XMLSyntaxError extends RuntimeException
{
  public XMLSyntaxError(String error)
  {
    super(error);
  }
  
  public XMLSyntaxError(String error, int lineNumber)
  {
    super(String.format("Line %d: %s", lineNumber, error));
  }

}